spring:
  profiles:
    include: oauth
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/comuDB
    username: comu
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use-new-id-generate-mappings: false
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 10MB

#comu.community.upload.path = /Users/hhwanseung/study/communityImage



logging.level:
  org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK


