server:
  port: 8080

spring:
  profiles:
    active: prod

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        use-new-id-generate-mappings: false
        show_sql: true
        format_sql: true
        use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 10MB

logging.level:
  org.hibernate.SQL: debug
#    org.hibernate.type: trace




